version: '3.8'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: shopify
      POSTGRES_USER: shopify
      POSTGRES_PASSWORD: shopify
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      BASE_URL: ${BASE_URL}
      SHOPIFY_SHOP: ${SHOPIFY_SHOP}
      SHOPIFY_ADMIN_TOKEN: ${SHOPIFY_ADMIN_TOKEN}
      SHOPIFY_WEBHOOK_SECRET: ${SHOPIFY_WEBHOOK_SECRET}
      SHOPIFY_API_VERSION: ${SHOPIFY_API_VERSION}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - "8080:8080"
    links:
      - db
volumes:
  db-data:
